kind = "web"
previewPath = "/"
title = "RayVPN Routers"
version = "1.0.0"
id = "artifacts/rayvpn-routers"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26071

[services.development]
run = "pnpm --filter @workspace/rayvpn-routers run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rayvpn-routers", "run", "build" ]
publicDir = "artifacts/rayvpn-routers/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26071"
BASE_PATH = "/"
